### ISSUE TITLE
try to auto-detect puns for insta-banning

### ISSUE THREAD

**Issue by gorel** [gorel/discord_dicebot#77]

**Comment by logan-stytch** [comment]
Fixed in https://github.com/gorel/discord_dicebot/commit/3f5304a6496aec48c1eaca7cfdc0c05cc4cc42c2

**Comment by gorel** [comment]
Fixed in https://github.com/gorel/discord_dicebot/commit/3f5304a6496aec48c1eaca7cfdc0c05cc4cc42c2
